[home]
title = "GeekNews"
url = "https://news.hada.io/"
entrySelector = "//tr[@class='topicinfo']/td[3]"
titleSelector = "//a[1]"
linkSelector = "//a[@class='u']"
waitUntil = "networkidle"

[origin]
title = "GeekNews ─ 원문"
url = "https://news.hada.io/"
entrySelector = "table tbody tr.topic"
titleSelector = "td.topictitle a h1"
linkSelector = "td.topictitle a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"

[new]
title = "GeekNews ─ 최신글"
url = "https://news.hada.io/new"
entrySelector = "//tr[@class='topicinfo']/td[3]"
titleSelector = "//a[1]"
linkSelector = "//a[@class='u']"
waitUntil = "networkidle"

[show]
title = "GeekNews Show"
url = "https://news.hada.io/show"
entrySelector = "td.topictitle"
titleSelector = "h1"
linkSelector = "a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"

[ask]
title = "GeekNews Ask"
url = "https://news.hada.io/ask"
entrySelector = "table tbody tr.topic"
titleSelector = "td.topictitle a h1"
linkSelector = "td.topictitle a"
contentSelector = "span.topicurl"
waitUntil = "networkidle"

[weekly]
title = "GeekNews Weekly"
url = "https://news.hada.io/weekly"
entrySelector = "table tbody tr.title"
titleSelector = "a.u.keepall"
linkSelector = "td a.u.keepall"
contentSelector = "tr.title"
waitUntil = "networkidle"

[podcast]
title = "GeekNews ─ Podcast"
url = "https://news.hada.io/podcast"
entrySelector = "tr.title"
titleSelector = "a.u.keepall"
linkSelector = "a.u.keepall"
contentSelector = "td.fitwidth:nth-child(1)"
dateSelector = "td.fitwidth:nth-child(2)"
dateFormat = "yyyy-MM-dd"
waitUntil = "networkidle"

[blog]
title = "GeekNews ─ Blog"
url = "https://news.hada.io/blog"
entrySelector = "tr.title"
titleSelector = "a.u.keepall"
linkSelector = "a.u.keepall"
contentSelector = "td.fitwidth:nth-child(1)"
dateSelector = "td.fitwidth:nth-child(2)"
dateFormat = "yyyy-MM-dd"
waitUntil = "networkidle"
