[new]
title = "GeekNews ─ 최신글"
url = "https://news.hada.io/new"
entrySelector = "div.topics div.topic_row"
titleSelector = "div.topictitle h1"
linkSelector = "div.topicinfo a.u"
waitUntil = "networkidle"

[show]
title = "GeekNews Show"
url = "https://news.hada.io/show"
entrySelector = "div.topic_row"
titleSelector = "div.topictitle h1"
linkSelector = "div.topictitle a"
contentSelector = "div.topicinfo a:nth-child(2)"
waitUntil = "networkidle"

[ask]
title = "GeekNews Ask"
url = "https://news.hada.io/ask"
entrySelector = "div.topic_row"
titleSelector = "div.topictitle h1"
linkSelector = "div.topictitle a"
contentSelector = "div.topicinfo a:nth-child(2)"
waitUntil = "networkidle"

[weekly]
title = "GeekNews Weekly"
url = "https://news.hada.io/weekly"
entrySelector = "div.weekly div a.u"
titleSelector = "a.u"
linkSelector = "*"
waitUntil = "networkidle"
